name: Slow cache
on: [workflow_dispatch]

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add Specs repository
        run: |
          gem install cocoapods
          pod repo add cocoapods https://github.com/CocoaPods/Specs.git

      - run: |
          du -sh ~/.cocoapods/repos/cocoapods

      - uses: actions/cache@v3
        with:
          path: ~/.cocoapods/repos/cocoapods
          key: ${{ runner.os }}-cocoapods-specs

  restore:
    name: Restore
    needs: generate
    runs-on: macos-latest
    steps:
      - name: restore cached large file
        uses: actions/cache@v3
        with:
          path: ~/.cocoapods/repos/cocoapods
          key: ${{ runner.os }}-cocoapods-specs
